### ISSUE TITLE
Install/Build Issue with v0.6.0

### ISSUE THREAD

**Issue by statikdev** [samuelvanderwaal/metaboss#117]
When upgrading to `v0.6.0`, I ran into installation and build issues as outlined below.

```
❯ rustc --version
rustc 1.56.0 (09c42c458 2021-10-18)
```

I didn't look too deeply into the the dependencies or error `E0658`. I was able to resolve the issue by upgrading rust to `1.60.0`. 

**Build Error**

```
   Compiling solana-faucet v1.9.16
   Compiling mpl-candy-machine v2.0.1
error[E0658]: panicking in constants is unstable
  --> /Users/statik/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-runtime-1.9.16/src/cost_tracker.rs:42:23
   |
42 |         const _: () = assert!(MAX_WRITABLE_ACCOUNT_UNITS <= MAX_BLOCK_UNITS);
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #51999 <https://github.com/rust-lang/rust/issues/51999> for more information
   = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: panicking in constants is unstable
  --> /Users/statik/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-runtime-1.9.16/src/cost_tracker.rs:43:23
   |
43 |         const _: () = assert!(MAX_VOTE_UNITS <= MAX_BLOCK_UNITS);
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #51999 <https://github.com/rust-lang/rust/issues/51999> for more information
   = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
error: could not compile `solana-runtime` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `metaboss v0.6.0 (/Users/statik/Development/ws/mb2)`, intermediate artifacts can be found at `/Users/statik/Development/ws/mb2/target`

Caused by:
  build failed
  ```

**Comment by samuelvanderwaal** [comment]
Looks like one our Metaplex dependency bumps uses a Solana package that requires a newer Rust version. Thanks for catching this. I was able to compile with Rust v1.58+.

**Comment by statikdev** [comment]
> Looks like one our Metaplex dependency bumps uses a Solana package that requires a newer Rust version. Thanks for catching this. I was able to compile with Rust v1.58+.

I was in a rush to fix metadata for something so I just yolo'd into 1.60. :)
